name: Release

on: [release]

jobs:

  publish:
    name: Build and publish Python distribution to PYPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install supporting packages
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install poetry

      - name: Show versions
        run: |
          uname -a
          python3 --version
          poetry --version

      - name: Build wheel and source tarball
        run: |
          poetry build

# stop at build; TODO: publish distribution to PIPI
